export const AFFILIATE_LINKS: Record<string, string> = {
  binance:    "https://binance.com",
  bybit:      "https://bybit.com",
  okx:        "https://okx.com",
  coinbase:   "https://coinbase.com",
  kraken:     "https://kraken.com",
  kucoin:     "https://kucoin.com",
  gateio:     "https://gate.io",
  bitget:     "https://bitget.com",
  mexc:       "https://mexc.com",
  htx:        "https://htx.com",
  cryptocom:  "https://crypto.com",
  bingx:      "https://bingx.com",
  bitfinex:   "https://bitfinex.com",
  phemex:     "https://phemex.com",
  gemini:     "https://gemini.com",
  deribit:    "https://deribit.com",
  woo:        "https://woo.org",
  poloniex:   "https://poloniex.com",
  coinex:     "https://coinex.com",
  ascendex:   "https://ascendex.com",
  whitebit:   "https://whitebit.com",
  lbank:      "https://lbank.com",
  xt:         "https://xt.com",
  bitrue:     "https://bitrue.com",
  probit:     "https://probit.com",
  digifinex:  "https://digifinex.com",
  bigone:     "https://bigone.com",
  latoken:    "https://latoken.com",
  delta:      "https://delta.exchange",
  zt:         "https://ztb.com",
};

export const EXCHANGE_DISPLAY: Array<{ id: string; name: string; color: string; tier: 1 | 2 }> = [
  { id: "binance",   name: "Binance",   color: "#F3BA2F", tier: 1 },
  { id: "bybit",     name: "Bybit",     color: "#F7A600", tier: 1 },
  { id: "okx",       name: "OKX",       color: "#FFFFFF", tier: 1 },
  { id: "coinbase",  name: "Coinbase",  color: "#0052FF", tier: 1 },
  { id: "kraken",    name: "Kraken",    color: "#5741D9", tier: 1 },
  { id: "kucoin",    name: "KuCoin",    color: "#00DA9D", tier: 1 },
  { id: "gateio",    name: "Gate.io",   color: "#2354E6", tier: 1 },
  { id: "bitget",    name: "Bitget",    color: "#00F0FF", tier: 1 },
  { id: "mexc",      name: "MEXC",      color: "#00B4FF", tier: 1 },
  { id: "htx",       name: "HTX",       color: "#347BFF", tier: 1 },
  { id: "cryptocom", name: "Crypto.com",color: "#002D74", tier: 1 },
  { id: "bingx",     name: "BingX",     color: "#1A56DB", tier: 1 },
  { id: "bitfinex",  name: "Bitfinex",  color: "#16B157", tier: 1 },
  { id: "phemex",    name: "Phemex",    color: "#0077FF", tier: 1 },
  { id: "gemini",    name: "Gemini",    color: "#00DCFA", tier: 1 },
  { id: "deribit",   name: "Deribit",   color: "#04CF5C", tier: 2 },
  { id: "woo",       name: "WOO",       color: "#7B2D8B", tier: 2 },
  { id: "poloniex",  name: "Poloniex",  color: "#1A8AFF", tier: 2 },
  { id: "coinex",    name: "CoinEx",    color: "#00A1FF", tier: 2 },
  { id: "ascendex",  name: "AscendEx", color: "#FA5151", tier: 2 },
  { id: "whitebit",  name: "WhiteBIT",  color: "#5CDB95", tier: 2 },
  { id: "lbank",     name: "LBank",     color: "#3375BB", tier: 2 },
  { id: "xt",        name: "XT.com",    color: "#22C0FF", tier: 2 },
  { id: "bitrue",    name: "Bitrue",    color: "#0D98F1", tier: 2 },
  { id: "probit",    name: "ProBit",    color: "#EF4F24", tier: 2 },
  { id: "digifinex", name: "DigiFinex", color: "#6200EA", tier: 2 },
  { id: "bigone",    name: "BigONE",    color: "#E23333", tier: 2 },
  { id: "latoken",   name: "LATOKEN",   color: "#3A86FF", tier: 2 },
  { id: "delta",     name: "Delta",     color: "#00C2A8", tier: 2 },
  { id: "zt",        name: "ZT",        color: "#FF6600", tier: 2 },
];
